# Generated by Django 4.2.26 on 2025-12-06 01:02

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_chatsession_chatmessage_documentembedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentversion",
            name="file",
            field=models.FileField(
                upload_to=documents.models.document_version_upload_path
            ),
        ),
    ]
