# Generated by Django 4.2.26 on 2026-04-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_add_chat_session_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="public_share_token",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
