# Generated by Django 4.2.13 on 2026-04-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_add_public_share_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="chat_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="documents.chatsession",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("document_shared", "Document Shared"),
                    ("document_updated", "Document Updated"),
                    ("comment_added", "Comment Added"),
                    ("comment_reply", "Comment Reply"),
                    ("permission_changed", "Permission Changed"),
                    ("mention", "Mentioned"),
                    ("chat_shared", "Chat Shared"),
                ],
                max_length=30,
            ),
        ),
    ]
