# Generated by Django 4.2.26 on 2026-04-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_add_chat_session_to_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="employee_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
